root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/servers/main.go"
bin = "tmp/main"
exclude_dir = ["tmp"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_file = []
delay = 1000 # ms
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
